### ISSUE TITLE
todo context II

### ISSUE THREAD

**Issue by Dripcoding** [Dripcoding/front-end-mentor-todo-app-react#14]
- [ ] - add reducer case for filtering all todos
- [ ] - add reducer case for filtering completed todos
- [ ] - add reducer case for filtering active todos
- [ ] - add reducer case for deleting all todos
- [ ] - add reducer case for marking a todo as active
- [ ] - add reducer case for marking a todo as completed
